import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Employee from '../components/employee'
import dayjs from 'dayjs'

function Board({ team }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Staff Movement Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <>
          <h2>
            Staff Movement Board - {team.name}
          </h2>
          <h4>{dayjs().format('DD MMM YYYY, dddd')}</h4>
        </>
        <table>
          <tbody>
            {team.list.map(e => <Employee key={e} id={e} />)}
          </tbody>
        </table>

      </>
    </div>
  )
}

export default Board