import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { list } from '../data/list'
import Employee from '../components/employee'

function refreshPage() {
  window.location.reload(false);
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Attendance Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <>
          <h2>
            Attendance board
          </h2>
          <button onClick={refreshPage}>refresh</button>
        </>

        <table>
          <tbody>
            {list.map(e => Employee(e))}
          </tbody>
        </table>

      </>
    </div>
  )
}
