import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { list } from '../data/list'
import Employee from '../components/employee'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Attendance Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <h2>
          Attendance board
        </h2>

        <table>
          <tbody>
            {list.map(e => Employee(e))}
          </tbody>
        </table>

      </>
    </div>
  )
}
